apiVersion: v1
kind: ConfigMap
metadata:
  name: kickstarter-config
data:
  LOG_LEVEL: "INFO"
  MODEL_PATH: artifact/model.joblib
  MLFLOW_TRACKING_URI: http://mlflow.mlops:5000
  MODEL_NAME: kickstarter
  MODEL_ALIAS: kek
